package com.mdzahidalam.myfinancetracker.export.model

/** Structured, renderer-independent document model used by premium PDF and XLSX exports. */
sealed interface ReportBlock {
    data class Heading(val text: String) : ReportBlock
    data class Field(val label: String, val value: String) : ReportBlock
    data class Paragraph(val text: String) : ReportBlock
    data class Table(val columns: List<String>, val rows: List<List<String>>) : ReportBlock
    data class Signature(val encodedImage: String) : ReportBlock
}

data class ReportDocument(
    val title: String,
    val subtitle: String = "",
    val status: String = "",
    val blocks: List<ReportBlock>,
    val footer: String = "Generated by My Finance Tracker • Powered by Md. Zahid Alam"
)

sealed interface FinanceDocument {
    val documentNumber: String
    val issuedAt: Long
    val blocks: List<ReportBlock>
}

data class ReceiptDocument(
    override val documentNumber: String,
    override val issuedAt: Long,
    val payer: String,
    val recipient: String,
    val amount: Double,
    val currencyCode: String,
    val status: String = "PAID",
    override val blocks: List<ReportBlock>
) : FinanceDocument

data class PaymentRequestDocument(
    override val documentNumber: String,
    override val issuedAt: Long,
    val requestedFrom: String,
    val amount: Double,
    val currencyCode: String,
    val dueAt: Long?,
    val status: String,
    override val blocks: List<ReportBlock>
) : FinanceDocument

data class SummaryReportDocument(
    override val documentNumber: String,
    override val issuedAt: Long,
    val period: String,
    override val blocks: List<ReportBlock>
) : FinanceDocument

data class DetailedFinanceDocument(
    override val documentNumber: String,
    override val issuedAt: Long,
    val period: String,
    override val blocks: List<ReportBlock>
) : FinanceDocument

object LegacyReportAdapter {
    /** Preserves every existing report field while the UI now renders semantic blocks. */
    fun fromText(text: String): ReportDocument {
        val lines = text.lines().dropWhile { it.equals("MY FINANCE TRACKER", true) }
        val blocks = lines.mapNotNull { raw ->
            val line = raw.trim()
            when {
                line.isEmpty() -> null
                line.startsWith("[[SIGNATURE:") && line.endsWith("]]" ) ->
                    ReportBlock.Signature(line.removePrefix("[[SIGNATURE:").removeSuffix("]]"))
                line == line.uppercase() && !line.contains(":") -> ReportBlock.Heading(line)
                line.contains(":") -> ReportBlock.Field(line.substringBefore(":").trim(), line.substringAfter(":").trim())
                else -> ReportBlock.Paragraph(line)
            }
        }
        val heading = blocks.filterIsInstance<ReportBlock.Heading>().firstOrNull()?.text ?: "FINANCE DOCUMENT"
        return ReportDocument(title = heading, blocks = blocks)
    }
}
