package com.mdzahidalam.myfinancetracker.feature.reports

import android.content.Context
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.util.Base64
import com.mdzahidalam.myfinancetracker.R
import com.mdzahidalam.myfinancetracker.localized
import com.mdzahidalam.myfinancetracker.localizedExport
import java.io.OutputStream
import java.util.Locale
import kotlin.math.max

/** A4 renderer shared by summary, detailed, receipt, and payment-request exports. */
internal object PremiumPdfRenderer {
    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val LEFT = 32f
    private const val RIGHT = 563f
    private const val CONTENT_TOP = 126f
    private const val CONTENT_BOTTOM = 780f

    private val teal = Color.rgb(0, 124, 122)
    private val darkTeal = Color.rgb(0, 82, 81)
    private val paleTeal = Color.rgb(226, 245, 242)
    private val ink = Color.rgb(35, 42, 42)
    private val muted = Color.rgb(92, 103, 102)
    private val soft = Color.rgb(247, 249, 249)
    private val border = Color.rgb(218, 226, 225)
    private val success = Color.rgb(24, 128, 82)
    private val warning = Color.rgb(174, 105, 0)
    private val danger = Color.rgb(176, 48, 48)

    private data class ParsedLine(val kind: Kind, val label: String = "", val value: String = "", val cells: List<String> = emptyList()) {
        enum class Kind { HEADING, FIELD, PARAGRAPH, TABLE_ROW, SIGNATURE }
    }

    fun write(context: Context, output: OutputStream, text: String) {
        val sourceLines = text.lines().map { localizedExport(it.trim()) }
        val documentTitle = sourceLines.firstOrNull { it.isNotBlank() }?.let(::localized) ?: localized("FINANCE REPORT")
        val documentType = when {
            documentTitle.contains("RECEIPT", true) || sourceLines.any { it.equals("PAYMENT RECEIPT", true) } -> "receipt"
            documentTitle.contains("REQUEST", true) || sourceLines.any { it.equals("PAYMENT REQUEST", true) } -> "request"
            documentTitle.contains("SUMMARY", true) -> "summary"
            else -> "detail"
        }
        val parsed = sourceLines.filter { it.isNotBlank() }.map(::parse)
        val pdf = PdfDocument()
        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        var pageNumber = 0
        lateinit var page: PdfDocument.Page
        lateinit var canvas: android.graphics.Canvas
        var y = CONTENT_TOP

        fun footer() {
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            paint.textSize = 8.5f
            paint.color = muted
            canvas.drawLine(LEFT, 798f, RIGHT, 798f, paint)
            canvas.drawText(localized("Generated by My Finance Tracker • Powered by Md. Zahid Alam"), LEFT, 819f, paint)
            val pageText = "${localized("Page")} $pageNumber"
            canvas.drawText(pageText, RIGHT - paint.measureText(pageText), 819f, paint)
        }

        fun header() {
            paint.color = teal
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 96f, paint)
            val logo = BitmapFactory.decodeResource(context.resources, R.drawable.app_logo)
            if (logo != null) canvas.drawBitmap(logo, null, RectF(28f, 16f, 92f, 80f), paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.color = Color.WHITE
            paint.textSize = 17f
            canvas.drawText(localized("MY FINANCE TRACKER"), 108f, 42f, paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            paint.textSize = 9.5f
            canvas.drawText(localized("Private • Offline • Secure"), 108f, 62f, paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.textSize = 9f
            val marker = when (documentType) {
                "receipt" -> localized("RECEIPT")
                "request" -> localized("PAYMENT REQUEST")
                "summary" -> localized("SUMMARY REPORT")
                else -> localized("DETAILED REPORT")
            }
            canvas.drawText(marker, RIGHT - paint.measureText(marker), 51f, paint)
        }

        fun newPage() {
            if (pageNumber > 0) {
                footer()
                pdf.finishPage(page)
            }
            pageNumber++
            page = pdf.startPage(PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create())
            canvas = page.canvas
            canvas.drawColor(Color.WHITE)
            header()
            y = CONTENT_TOP
        }

        fun ensure(height: Float) {
            if (y + height > CONTENT_BOTTOM) newPage()
        }

        fun wrap(value: String, width: Float, size: Float = paint.textSize): List<String> {
            paint.textSize = size
            if (value.isBlank()) return listOf("")
            val result = mutableListOf<String>()
            var current = ""
            value.split(Regex("\\s+")).forEach { word ->
                if (paint.measureText(word) > width) {
                    if (current.isNotBlank()) { result += current; current = "" }
                    var fragment = ""
                    word.forEach { character ->
                        val candidate = fragment + character
                        if (paint.measureText(candidate) > width && fragment.isNotEmpty()) {
                            result += fragment
                            fragment = character.toString()
                        } else fragment = candidate
                    }
                    current = fragment
                    return@forEach
                }
                val candidate = if (current.isBlank()) word else "$current $word"
                if (paint.measureText(candidate) > width && current.isNotBlank()) {
                    result += current
                    current = word
                } else current = candidate
            }
            if (current.isNotBlank()) result += current
            return result.ifEmpty { listOf(value) }
        }

        fun drawTitle(title: String, subtitle: String?) {
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.color = ink
            paint.textSize = 22f
            wrap(title, RIGHT - LEFT, 22f).forEach { line -> canvas.drawText(line, LEFT, y, paint); y += 27f }
            if (!subtitle.isNullOrBlank()) {
                paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                paint.color = muted
                paint.textSize = 10f
                canvas.drawText(subtitle, LEFT, y + 2f, paint)
                y += 24f
            } else y += 8f
        }

        fun drawHeading(value: String) {
            ensure(50f)
            y += 7f
            paint.color = paleTeal
            canvas.drawRoundRect(LEFT, y - 20f, RIGHT, y + 13f, 8f, 8f, paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.color = darkTeal
            paint.textSize = 12.5f
            canvas.drawText(value, LEFT + 12f, y + 1f, paint)
            y += 30f
        }

        fun drawField(label: String, value: String, emphasized: Boolean = false) {
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val valueLines = wrap(value, 337f, if (emphasized) 15f else 10f)
            val rowHeight = max(if (emphasized) 48f else 34f, valueLines.size * (if (emphasized) 19f else 14f) + 15f)
            ensure(rowHeight + 5f)
            paint.color = if (emphasized) paleTeal else soft
            canvas.drawRoundRect(LEFT, y, RIGHT, y + rowHeight, 7f, 7f, paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.color = muted
            paint.textSize = 9f
            canvas.drawText(label, LEFT + 12f, y + 20f, paint)
            paint.typeface = Typeface.create(Typeface.DEFAULT, if (emphasized) Typeface.BOLD else Typeface.NORMAL)
            paint.color = if (emphasized) darkTeal else ink
            paint.textSize = if (emphasized) 15f else 10f
            valueLines.forEachIndexed { index, line -> canvas.drawText(line, LEFT + 190f, y + 20f + index * (if (emphasized) 19f else 14f), paint) }
            y += rowHeight + 5f
        }

        fun drawParagraph(value: String) {
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            paint.color = ink
            paint.textSize = 9.5f
            val lines = wrap(value, RIGHT - LEFT - 20f, 9.5f)
            ensure(lines.size * 14f + 16f)
            lines.forEach { line -> canvas.drawText(line, LEFT + 6f, y + 12f, paint); y += 14f }
            y += 5f
        }

        fun drawTableRow(cells: List<String>, stripe: Boolean) {
            val widths = listOf(48f, 152f, 108f, 108f, 105f)
            val normalized = cells.take(5)
            val wrapped = normalized.mapIndexed { index, cell -> wrap(cell, widths[index] - 10f, 8.5f) }
            val height = max(30f, (wrapped.maxOfOrNull { it.size } ?: 1) * 12f + 12f)
            ensure(height + 2f)
            paint.color = if (stripe) soft else Color.WHITE
            canvas.drawRect(LEFT, y, RIGHT, y + height, paint)
            paint.color = border
            canvas.drawLine(LEFT, y + height, RIGHT, y + height, paint)
            var x = LEFT
            wrapped.forEachIndexed { index, lines ->
                paint.typeface = Typeface.create(Typeface.DEFAULT, if (index == 0) Typeface.BOLD else Typeface.NORMAL)
                paint.color = if (index == 0) darkTeal else ink
                paint.textSize = 8.5f
                lines.forEachIndexed { lineIndex, line -> canvas.drawText(line, x + 5f, y + 14f + lineIndex * 12f, paint) }
                x += widths[index]
            }
            y += height
        }

        fun drawSignature(encoded: String) {
            val signature = runCatching {
                val bytes = Base64.decode(encoded, Base64.NO_WRAP)
                BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
            }.getOrNull() ?: return
            ensure(112f)
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.color = muted
            paint.textSize = 9f
            canvas.drawText(localized("AUTHORIZED SIGNATURE"), LEFT, y + 14f, paint)
            val ratio = signature.width.toFloat() / signature.height.coerceAtLeast(1)
            val imageHeight = 58f
            val imageWidth = minOf(175f, imageHeight * ratio)
            canvas.drawBitmap(signature, null, RectF(LEFT, y + 22f, LEFT + imageWidth, y + 22f + imageHeight), paint)
            paint.color = muted
            canvas.drawLine(LEFT, y + 88f, LEFT + 195f, y + 88f, paint)
            y += 104f
        }

        newPage()
        val visibleTitle = parsed.firstOrNull {
            it.kind == ParsedLine.Kind.HEADING && !it.label.equals(localized("MY FINANCE TRACKER"), true)
        }?.label ?: documentTitle
        val subtitle = parsed.firstOrNull { it.kind == ParsedLine.Kind.FIELD && it.label in listOf("Generated", "Payment date", "Request date") }
            ?.let { "${it.label}: ${it.value}" }
        drawTitle(visibleTitle, subtitle)

        var tableStripe = false
        parsed.forEach { item ->
            if (item.kind == ParsedLine.Kind.HEADING &&
                (item.label.equals(localized("MY FINANCE TRACKER"), true) || item.label == visibleTitle)
            ) return@forEach
            when (item.kind) {
                ParsedLine.Kind.HEADING -> drawHeading(item.label)
                ParsedLine.Kind.FIELD -> {
                    val emphasize = item.label.equals("Amount", true) || item.label.equals("Amount requested", true) || item.label.equals("Expense total", true)
                    if (item.label == "Request status" || item.label == "Status") {
                        ensure(34f)
                        val statusColor = when {
                            item.value.contains("PAID", true) || item.value.contains("COMPLETED", true) -> success
                            item.value.contains("CANCEL", true) || item.value.contains("OVERDUE", true) -> danger
                            else -> warning
                        }
                        paint.color = statusColor
                        canvas.drawRoundRect(LEFT, y, LEFT + 126f, y + 26f, 13f, 13f, paint)
                        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                        paint.color = Color.WHITE
                        paint.textSize = 9f
                        val statusText = item.value.uppercase(Locale.getDefault())
                        canvas.drawText(statusText, LEFT + 12f, y + 17f, paint)
                        y += 34f
                    } else drawField(item.label, item.value, emphasize)
                }
                ParsedLine.Kind.PARAGRAPH -> drawParagraph(item.value)
                ParsedLine.Kind.TABLE_ROW -> { drawTableRow(item.cells, tableStripe); tableStripe = !tableStripe }
                ParsedLine.Kind.SIGNATURE -> drawSignature(item.value)
            }
        }
        footer()
        pdf.finishPage(page)
        pdf.writeTo(output)
        pdf.close()
    }

    private fun parse(line: String): ParsedLine = when {
        line.startsWith("[[SIGNATURE:") && line.endsWith("]]" ) -> ParsedLine(ParsedLine.Kind.SIGNATURE, value = line.removePrefix("[[SIGNATURE:").removeSuffix("]]"))
        line.contains("|") -> ParsedLine(ParsedLine.Kind.TABLE_ROW, cells = line.split("|").map { it.trim() })
        line == line.uppercase(Locale.getDefault()) && !line.contains(":") -> ParsedLine(ParsedLine.Kind.HEADING, label = localized(line))
        line.contains(":") -> ParsedLine(ParsedLine.Kind.FIELD, label = localized(line.substringBefore(":").trim()), value = localized(line.substringAfter(":").trim()))
        else -> ParsedLine(ParsedLine.Kind.PARAGRAPH, value = localized(line))
    }
}
