package com.mdzahidalam.myfinancetracker.feature.reports

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.util.Base64
import com.mdzahidalam.myfinancetracker.R
import com.mdzahidalam.myfinancetracker.localized
import com.mdzahidalam.myfinancetracker.localizedExport
import java.io.OutputStream
import java.util.Locale
import kotlin.math.max

/** Premium A4 renderer shared by reports, receipts, and payment requests. */
internal object PremiumPdfRenderer {
    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val LEFT = 32f
    private const val RIGHT = 563f
    private const val TOP = 116f
    private const val BOTTOM = 782f

    private val teal = Color.rgb(0, 124, 122)
    private val darkTeal = Color.rgb(0, 82, 81)
    private val paleTeal = Color.rgb(226, 245, 242)
    private val ink = Color.rgb(35, 42, 42)
    private val muted = Color.rgb(92, 103, 102)
    private val soft = Color.rgb(247, 249, 249)
    private val border = Color.rgb(218, 226, 225)
    private val success = Color.rgb(24, 128, 82)
    private val warning = Color.rgb(174, 105, 0)
    private val danger = Color.rgb(176, 48, 48)
    private val neutral = Color.rgb(84, 96, 107)

    private data class ParsedLine(
        val kind: Kind,
        val label: String = "",
        val value: String = "",
        val cells: List<String> = emptyList()
    ) {
        enum class Kind { HEADING, FIELD, PARAGRAPH, TABLE_ROW, SIGNATURE }
    }

    fun write(context: Context, output: OutputStream, text: String) {
        val lines = text.lines().map { localizedExport(it.trim()) }.filter { it.isNotBlank() }
        val type = when {
            lines.any { it.equals("PAYMENT RECEIPT", true) } -> "receipt"
            lines.any { it.equals("PAYMENT REQUEST", true) } -> "request"
            lines.any { it.contains("SUMMARY REPORT", true) } -> "summary"
            else -> "detail"
        }
        val state = State(context, type)
        val parsed = lines.map(::parse)
        if (type == "receipt" || type == "request") state.renderTransaction(parsed)
        else state.renderReport(parsed)
        state.finish(output)
    }

    private class State(context: Context, private val type: String) {
        private val pdf = PdfDocument()
        private val logo: Bitmap? = BitmapFactory.decodeResource(context.resources, R.drawable.app_logo)
        private var pageNumber = 0
        private lateinit var page: PdfDocument.Page
        private lateinit var canvas: android.graphics.Canvas
        private var y = TOP
        private var activeTableHeader: List<String>? = null
        private var tableStripe = false

        private fun paint(color: Int, size: Float, bold: Boolean = false) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            this.color = color
            textSize = size
            typeface = Typeface.create(Typeface.DEFAULT, if (bold) Typeface.BOLD else Typeface.NORMAL)
        }

        private fun marker(): String = when (type) {
            "receipt" -> localized("RECEIPT")
            "request" -> localized("PAYMENT REQUEST")
            "summary" -> localized("SUMMARY REPORT")
            else -> localized("DETAILED REPORT")
        }

        private fun header() {
            canvas.save()
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 88f, paint(teal, 1f))
            logo?.let { canvas.drawBitmap(it, null, RectF(28f, 12f, 92f, 76f), Paint(Paint.ANTI_ALIAS_FLAG)) }
            canvas.drawText(localized("MY FINANCE TRACKER"), 108f, 38f, paint(Color.WHITE, 17f, true))
            canvas.drawText(localized("Private • Offline • Secure"), 108f, 58f, paint(Color.WHITE, 9.5f))
            val labelPaint = paint(Color.WHITE, 9f, true)
            val label = marker()
            canvas.drawText(label, RIGHT - labelPaint.measureText(label), 45f, labelPaint)
            canvas.restore()
        }

        private fun footer() {
            canvas.save()
            canvas.drawLine(LEFT, 800f, RIGHT, 800f, paint(border, 1f))
            val footerPaint = paint(muted, 8f)
            canvas.drawText(localized("Generated by My Finance Tracker • Powered by Md. Zahid Alam"), LEFT, 820f, footerPaint)
            val number = "${localized("Page")} $pageNumber"
            canvas.drawText(number, RIGHT - footerPaint.measureText(number), 820f, footerPaint)
            canvas.restore()
        }

        private fun startPage(repeatTableHeader: Boolean = false) {
            if (pageNumber > 0) {
                footer()
                pdf.finishPage(page)
            }
            pageNumber++
            page = pdf.startPage(PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create())
            canvas = page.canvas
            canvas.drawColor(Color.WHITE)
            header()
            y = TOP
            if (repeatTableHeader) activeTableHeader?.let {
                canvas.drawText(localized("Continued"), LEFT, y + 10f, paint(muted, 8f, true))
                y += 16f
                drawTableRow(it, header = true, allowBreak = false)
            }
        }

        private fun ensure(height: Float, tableContinuation: Boolean = false) {
            if (y + height > BOTTOM) startPage(tableContinuation)
        }

        private fun wrap(value: String, width: Float, size: Float, bold: Boolean = false): List<String> {
            val measure = paint(ink, size, bold)
            if (value.isBlank()) return emptyList()
            val output = mutableListOf<String>()
            var line = ""
            value.split(Regex("\\s+")).forEach { word ->
                if (measure.measureText(word) > width) {
                    if (line.isNotBlank()) { output += line; line = "" }
                    var fragment = ""
                    word.forEach { character ->
                        val candidate = fragment + character
                        if (measure.measureText(candidate) > width && fragment.isNotBlank()) {
                            output += fragment
                            fragment = character.toString()
                        } else fragment = candidate
                    }
                    line = fragment
                } else {
                    val candidate = if (line.isBlank()) word else "$line $word"
                    if (measure.measureText(candidate) > width && line.isNotBlank()) {
                        output += line
                        line = word
                    } else line = candidate
                }
            }
            if (line.isNotBlank()) output += line
            return output
        }

        private fun title(value: String, subtitle: String? = null) {
            val titleLines = wrap(value, RIGHT - LEFT, 21f, true)
            ensure(titleLines.size * 25f + 26f)
            titleLines.forEach { canvas.drawText(it, LEFT, y + 18f, paint(ink, 21f, true)); y += 25f }
            subtitle?.takeIf { it.isNotBlank() }?.let {
                canvas.drawText(it, LEFT, y + 3f, paint(muted, 9.5f))
                y += 18f
            }
            y += 4f
        }

        private fun section(value: String) {
            activeTableHeader = null
            tableStripe = false
            ensure(52f)
            y += 7f
            canvas.drawRoundRect(LEFT, y, RIGHT, y + 32f, 8f, 8f, paint(paleTeal, 1f))
            canvas.drawText(value, LEFT + 12f, y + 21f, paint(darkTeal, 12f, true))
            y += 40f
        }

        private fun fieldHeight(value: String, width: Float): Float =
            max(39f, wrap(value, width - 20f, 9.5f).size * 13f + 18f)

        private fun fieldCard(item: ParsedLine, x: Float, width: Float, height: Float) {
            canvas.drawRoundRect(x, y, x + width, y + height, 7f, 7f, paint(soft, 1f))
            canvas.drawText(item.label, x + 10f, y + 14f, paint(muted, 8f, true))
            val valuePaint = paint(ink, 9.5f)
            wrap(item.value, width - 20f, 9.5f).take(3).forEachIndexed { index, line ->
                canvas.drawText(line, x + 10f, y + 29f + index * 12f, valuePaint)
            }
        }

        private fun fieldPair(first: ParsedLine, second: ParsedLine? = null) {
            val gap = 8f
            val width = (RIGHT - LEFT - gap) / 2f
            val height = max(fieldHeight(first.value, width), second?.let { fieldHeight(it.value, width) } ?: 0f)
            ensure(height + 6f)
            fieldCard(first, LEFT, if (second == null) RIGHT - LEFT else width, height)
            second?.let { fieldCard(it, LEFT + width + gap, width, height) }
            y += height + 6f
        }

        private fun amountHero(item: ParsedLine) {
            ensure(58f)
            canvas.drawRoundRect(LEFT, y, RIGHT, y + 52f, 10f, 10f, paint(paleTeal, 1f))
            canvas.drawText(item.label.uppercase(Locale.getDefault()), LEFT + 14f, y + 18f, paint(muted, 8.5f, true))
            canvas.drawText(item.value, LEFT + 14f, y + 42f, paint(darkTeal, 18f, true))
            y += 58f
        }

        private fun statusBadge(value: String) {
            ensure(30f)
            val color = when {
                value.equals("PAID", true) || value.equals("COMPLETED", true) -> success
                value.contains("PART", true) || value.equals("PENDING", true) || value.equals("UNPAID", true) -> warning
                value.contains("CANCEL", true) || value.contains("OVERDUE", true) -> danger
                else -> neutral
            }
            val badgePaint = paint(Color.WHITE, 8.5f, true)
            val label = value.uppercase(Locale.getDefault())
            val width = max(92f, badgePaint.measureText(label) + 28f)
            canvas.drawRoundRect(LEFT, y, LEFT + width, y + 24f, 12f, 12f, paint(color, 1f))
            canvas.drawText(label, LEFT + 14f, y + 16f, badgePaint)
            y += 30f
        }

        private fun paragraph(value: String, disclaimer: Boolean = false) {
            val size = if (disclaimer) 8.2f else 9.2f
            val lines = wrap(value, RIGHT - LEFT - 16f, size)
            ensure(lines.size * 12f + 10f)
            lines.forEach { canvas.drawText(it, LEFT + 4f, y + 10f, paint(if (disclaimer) muted else ink, size)); y += 12f }
            y += 4f
        }

        private fun tableWidths(count: Int): List<Float> = when (count) {
            3 -> listOf(60f, 300f, 171f)
            4 -> listOf(48f, 154f, 108f, 221f)
            else -> List(count.coerceAtLeast(1)) { (RIGHT - LEFT) / count.coerceAtLeast(1) }
        }

        private fun drawTableRow(cells: List<String>, header: Boolean, allowBreak: Boolean = true) {
            val widths = tableWidths(cells.size)
            val wrapped = cells.mapIndexed { index, cell -> wrap(cell, widths[index] - 10f, 8.2f, header || index == 0) }
            val height = max(if (header) 28f else 25f, (wrapped.maxOfOrNull { it.size } ?: 1) * 11f + 10f)
            if (allowBreak && y + height > BOTTOM) startPage(repeatTableHeader = !header)
            canvas.drawRect(LEFT, y, RIGHT, y + height, paint(if (header) paleTeal else if (tableStripe) soft else Color.WHITE, 1f))
            var x = LEFT
            wrapped.forEachIndexed { index, values ->
                val textPaint = paint(if (header || index == 0) darkTeal else ink, 8.2f, header || index == 0)
                values.forEachIndexed { lineIndex, line -> canvas.drawText(line, x + 5f, y + 14f + lineIndex * 11f, textPaint) }
                x += widths[index]
            }
            canvas.drawLine(LEFT, y + height, RIGHT, y + height, paint(border, 1f))
            y += height
            if (!header) tableStripe = !tableStripe
        }

        private fun signature(encoded: String, compact: Boolean = false) {
            val bitmap = runCatching {
                val bytes = Base64.decode(encoded, Base64.NO_WRAP)
                BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
            }.getOrNull() ?: return
            val blockHeight = if (compact) 76f else 94f
            ensure(blockHeight)
            canvas.drawText(localized("AUTHORIZED SIGNATURE"), LEFT, y + 12f, paint(muted, 8f, true))
            val imageHeight = if (compact) 42f else 54f
            val ratio = bitmap.width.toFloat() / bitmap.height.coerceAtLeast(1)
            val imageWidth = minOf(165f, imageHeight * ratio)
            canvas.drawBitmap(bitmap, null, RectF(LEFT, y + 17f, LEFT + imageWidth, y + 17f + imageHeight), Paint(Paint.ANTI_ALIAS_FLAG))
            canvas.drawLine(LEFT, y + blockHeight - 8f, LEFT + 190f, y + blockHeight - 8f, paint(muted, 1f))
            y += blockHeight
        }

        fun renderTransaction(items: List<ParsedLine>) {
            startPage()
            val heading = items.firstOrNull { it.kind == ParsedLine.Kind.HEADING && !it.label.equals(localized("MY FINANCE TRACKER"), true) }
                ?.label ?: marker()
            val fields = items.filter { it.kind == ParsedLine.Kind.FIELD && it.value.isNotBlank() }
            val documentNumber = fields.firstOrNull { it.label.contains("number", true) }
            val date = fields.firstOrNull { it.label.equals("Payment date", true) || it.label.equals("Request date", true) }
            title(heading, listOfNotNull(documentNumber?.value, date?.value).joinToString("  •  "))

            val status = fields.firstOrNull { it.label.contains("status", true) }
            status?.let { statusBadge(it.value) }
            val amount = fields.firstOrNull { it.label.equals("Amount", true) || it.label.equals("Amount requested", true) }
            amount?.let(::amountHero)

            val skipped = listOfNotNull(documentNumber, date, status, amount).toSet()
            val remaining = fields.filterNot { it in skipped }
            var index = 0
            while (index < remaining.size) {
                fieldPair(remaining[index], remaining.getOrNull(index + 1))
                index += 2
            }
            items.filter { it.kind == ParsedLine.Kind.PARAGRAPH }.forEach { paragraph(it.value, disclaimer = true) }
            items.firstOrNull { it.kind == ParsedLine.Kind.SIGNATURE }?.let { signature(it.value, compact = true) }
        }

        fun renderReport(items: List<ParsedLine>) {
            startPage()
            val visibleTitle = items.firstOrNull {
                it.kind == ParsedLine.Kind.HEADING && !it.label.equals(localized("MY FINANCE TRACKER"), true)
            }?.label ?: marker()
            val generated = items.firstOrNull { it.kind == ParsedLine.Kind.FIELD && it.label.equals("Generated", true) }
            title(visibleTitle, generated?.value)

            var pendingField: ParsedLine? = null
            fun flushPending() { pendingField?.let { fieldPair(it) }; pendingField = null }

            items.forEach { item ->
                if (item.kind == ParsedLine.Kind.HEADING &&
                    (item.label.equals(localized("MY FINANCE TRACKER"), true) || item.label == visibleTitle)
                ) return@forEach
                if (item.kind == ParsedLine.Kind.FIELD && item.label.equals("Generated", true)) return@forEach
                when (item.kind) {
                    ParsedLine.Kind.HEADING -> { flushPending(); section(item.label) }
                    ParsedLine.Kind.FIELD -> {
                        if (item.value.isBlank()) return@forEach
                        val emphasized = type == "summary" && listOf("Expense total", "EMI remaining", "Loan remaining", "Debt to pay", "Money to receive").any { item.label.equals(it, true) }
                        if (emphasized) { flushPending(); amountHero(item) }
                        else if (pendingField == null) pendingField = item
                        else { fieldPair(pendingField!!, item); pendingField = null }
                    }
                    ParsedLine.Kind.PARAGRAPH -> { flushPending(); paragraph(item.value) }
                    ParsedLine.Kind.TABLE_ROW -> {
                        flushPending()
                        val isHeader = item.cells.firstOrNull()?.equals("No.", true) == true || item.cells.firstOrNull()?.equals("Date", true) == true
                        if (isHeader) { activeTableHeader = item.cells; tableStripe = false }
                        drawTableRow(item.cells, header = isHeader)
                    }
                    ParsedLine.Kind.SIGNATURE -> { flushPending(); signature(item.value) }
                }
            }
            flushPending()
        }

        fun finish(output: OutputStream) {
            if (pageNumber == 0) startPage()
            footer()
            pdf.finishPage(page)
            pdf.writeTo(output)
            pdf.close()
        }
    }

    private fun parse(line: String): ParsedLine = when {
        line.startsWith("[[SIGNATURE:") && line.endsWith("]]" ) ->
            ParsedLine(ParsedLine.Kind.SIGNATURE, value = line.removePrefix("[[SIGNATURE:").removeSuffix("]]"))
        line.contains("|") -> ParsedLine(ParsedLine.Kind.TABLE_ROW, cells = line.split("|").map { it.trim() })
        line == line.uppercase(Locale.getDefault()) && !line.contains(":") ->
            ParsedLine(ParsedLine.Kind.HEADING, label = localized(line))
        line.contains(":") -> ParsedLine(
            ParsedLine.Kind.FIELD,
            label = localized(line.substringBefore(":").trim()),
            value = localized(line.substringAfter(":").trim())
        )
        else -> ParsedLine(ParsedLine.Kind.PARAGRAPH, value = localized(line))
    }
}
